"""
Hourly Data Fallback
====================
This script is a safety fallback only.
Real hourly_data.json is generated by generate_activity_time.py using actual event timestamps.
This script does NOTHING if hourly_data.json already exists (real data takes priority).
"""

import os
import json

def generate_hourly():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root_dir = os.path.dirname(script_dir)
    dash_dir = os.path.join(root_dir, 'dashboard')

    out_path = os.path.join(dash_dir, 'hourly_data.json')

    # Real data is written by generate_activity_time.py — never overwrite it.
    if os.path.exists(out_path):
        with open(out_path, 'r', encoding='utf-8') as f:
            try:
                data = json.load(f)
                if data:
                    print(f"[build_hourly] Real hourly_data.json already exists ({len(data)} records). Skipping.")
                    return
            except json.JSONDecodeError:
                pass  # File is corrupt — fall through to write empty placeholder

    # Only reached if hourly_data.json is missing or corrupt.
    print("[build_hourly] No hourly_data.json found. Writing empty placeholder.")
    os.makedirs(dash_dir, exist_ok=True)
    with open(out_path, 'w', encoding='utf-8') as f:
        json.dump([], f)

if __name__ == "__main__":
    generate_hourly()
